### ISSUE TITLE
Using API provided pagination to build the view

### ISSUE THREAD

**Issue by jmpala** [JoshuaSchumacherGER/Pokedex#6]
We can use the pagination functionality of the API, to retrieve a controlled amount of resources and don't rush on the API quotas (if any). Or is it by design that there should be a huge load of all needed API resources per view at the beginning of each page, catching them or saving them locally for later use?

**Comment by JoshuaSchumacherGER** [comment]
Indeed, it is currently intended 'by design'. However, you are welcome to limit the amount of data and speed up the structure. In that case, I would ask you to either leave the old code in the file and briefly explain in a comment within the file why there was a change OR create a new .js file and rename the old one (legacy), especially if larger parts of the code are being changed.

Don't forget: This version of the Pokedex is deliberately implemented in a very simple way so that even beginners can understand what is happening. Therefore, no framework, databases, or anything similar is used in the original version. If you think of something that could improve the Pokedex (UI enhancemen, database integration, import/export functions, etc.), feel free to open a case. It is also possible - purely for learning purposes - to work with Vue, React, and similar frameworks, and to accordingly expand the project
